apiVersion: batch/v1
kind: Job
metadata:
  name: time-limit 
  namespace: stage
spec:
  template:
    metadata: 
      name: time-limit
      labels:
        app: stage
    spec:
      containers:
      - name: {}
        image: {}
        ports:
        - containerPort: {}
        resources: {}
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 30"] 
      restartPolicy: Never
      terminationGracePeriodSeconds: 60 # 파드가 삭제되기 전에 컨테이너에게 종료 대기 시간
  backoffLimit: 0 # 작업이 실패한 경우 재시도 횟수를 지정
  activeDeadlineSeconds: 500 # job 작업 시간
  ttlSecondsAfterFinished: 30 # job 작업 완료 후 삭제
